// Master Indian Real Estate Data Store
// Provides realistic enterprise-grade Indian real estate data for all 20+ pages and fallback service integration.

export const INDIAN_CITIES = [
  "Hyderabad",
  "Bengaluru",
  "Chennai",
  "Mumbai",
  "Pune",
  "Delhi",
  "Ahmedabad",
  "Visakhapatnam",
  "Coimbatore",
  "Kochi",
];

export const INDIAN_PROPERTIES = [
  {
    propertyId: 1001,
    id: "PR-1001",
    numericId: 1001,
    propertyName: "Gachibowli Tech Park Phase 2",
    title: "Gachibowli Tech Park Phase 2",
    ownerName: "Ananya Rao",
    owner: "Ananya Rao",
    address: {
      addressLine1: "Plot 45, Sy. No. 112/A, Financial District",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500032",
      country: "India",
    },
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500032",
    surveyNumber: "Sy. No. 112/A",
    registrationNumber: "REG/HYD/2023/8891",
    deedNumber: "DEED/TS/2023/4412",
    totalArea: 45000,
    area: "45,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 250000000, // ₹25.00 Cr
    score: "₹25.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 14,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2021,
    year: 2021,
    createdByEmail: "ananya.rao@apexdiligence.in",
    description: "Grade-A IT/ITES commercial land parcel situated in Nanakramguda Financial District with 100% clear title verification from Serilingampally Sub-Registrar.",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1002,
    id: "PR-1002",
    numericId: 1002,
    propertyName: "Jubilee Hills Luxury Enclave",
    title: "Jubilee Hills Luxury Enclave",
    ownerName: "Vikramaditya Reddy",
    owner: "Vikramaditya Reddy",
    address: {
      addressLine1: "Road No. 36, Plot 118",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500033",
      country: "India",
    },
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500033",
    surveyNumber: "Sy. No. 403/2",
    registrationNumber: "REG/HYD/2022/3310",
    deedNumber: "DEED/TS/2022/9901",
    totalArea: 12500,
    area: "12,500 sq ft",
    landType: "Residential",
    type: "Residential",
    marketValue: 185000000, // ₹18.50 Cr
    score: "₹18.50 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 18,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2019,
    year: 2019,
    createdByEmail: "vikram.reddy@apexdiligence.in",
    description: "Prime residential plot in Jubilee Hills Road No. 36 with verified GHMC building plans and nil encumbrance certificate.",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1003,
    id: "PR-1003",
    numericId: 1003,
    propertyName: "Whitefield Outer Ring Road Tech Hub",
    title: "Whitefield Outer Ring Road Tech Hub",
    ownerName: "Suresh Patel",
    owner: "Suresh Patel",
    address: {
      addressLine1: "Survey 84/2, ORR Whitefield Road",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560066",
      country: "India",
    },
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560066",
    surveyNumber: "Sy. No. 84/2",
    registrationNumber: "REG/BLR/2024/7741",
    deedNumber: "DEED/KA/2024/1102",
    totalArea: 65000,
    area: "65,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 320000000, // ₹32.00 Cr
    score: "₹32.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 22,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2022,
    year: 2022,
    createdByEmail: "suresh.patel@apexdiligence.in",
    description: "High-density tech corridor parcel adjacent to Kadubeesanahalli Metro Station. BBMP A-Katha verified with 3.5 FAR permission.",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1004,
    id: "PR-1004",
    numericId: 1004,
    propertyName: "Bandra Kurla Complex Corporate Tower",
    title: "Bandra Kurla Complex Corporate Tower",
    ownerName: "Venkatesh Iyer",
    owner: "Venkatesh Iyer",
    address: {
      addressLine1: "Plot 18, Block G, BKC Complex",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400051",
      country: "India",
    },
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400051",
    surveyNumber: "CTS No. 441/B",
    registrationNumber: "REG/MAH/2023/9012",
    deedNumber: "DEED/MH/2023/8811",
    totalArea: 38000,
    area: "38,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 450000000, // ₹45.00 Cr
    score: "₹45.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 12,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2020,
    year: 2020,
    createdByEmail: "venkatesh.iyer@apexdiligence.in",
    description: "Premium BKC commercial land parcel with MMRDA leasehold clearance valid for 99 years and full environmental clearance.",
    imageUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1005,
    id: "PR-1005",
    numericId: 1005,
    propertyName: "OMR IT Corridor Parcel A",
    title: "OMR IT Corridor Parcel A",
    ownerName: "Kavitha Nair",
    owner: "Kavitha Nair",
    address: {
      addressLine1: "TS No. 44/1, Thoraipakkam, OMR",
      city: "Chennai",
      state: "Tamil Nadu",
      postalCode: "600096",
      country: "India",
    },
    city: "Chennai",
    state: "Tamil Nadu",
    postalCode: "600096",
    surveyNumber: "TS No. 44/1",
    registrationNumber: "REG/CHE/2023/1245",
    deedNumber: "DEED/TN/2023/5021",
    totalArea: 28000,
    area: "28,000 sq ft",
    landType: "Mixed-Use",
    type: "Mixed-Use",
    marketValue: 142000000, // ₹14.20 Cr
    score: "₹14.20 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 28,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2021,
    year: 2021,
    createdByEmail: "kavitha.nair@apexdiligence.in",
    description: "CMDA approved mixed-use parcel along Old Mahabalipuram Road with verified Patta & Chitta documents.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1006,
    id: "PR-1006",
    numericId: 1006,
    propertyName: "Viman Nagar Business Suites",
    title: "Viman Nagar Business Suites",
    ownerName: "Aditi Deshmukh",
    owner: "Aditi Deshmukh",
    address: {
      addressLine1: "Sy. No. 204, Near Pune Airport Road",
      city: "Pune",
      state: "Maharashtra",
      postalCode: "411014",
      country: "India",
    },
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411014",
    surveyNumber: "Sy. No. 204/1A",
    registrationNumber: "REG/PUN/2024/7781",
    deedNumber: "DEED/MH/2024/3321",
    totalArea: 22000,
    area: "22,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 168000000, // ₹16.80 Cr
    score: "₹16.80 Cr",
    status: "Minor Variance Pending",
    variant: "warning",
    riskScore: 42,
    riskLevel: "Moderate Risk",
    riskStatus: "MEDIUM",
    builtYear: 2018,
    year: 2018,
    createdByEmail: "aditi.deshmukh@apexdiligence.in",
    description: "PMC commercial land in Viman Nagar. Structural fire safety clearance audit complete; setback NOC awaiting signoff.",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1007,
    id: "PR-1007",
    numericId: 1007,
    propertyName: "SG Highway Corporate Park",
    title: "SG Highway Corporate Park",
    ownerName: "Arvind Kumar",
    owner: "Arvind Kumar",
    address: {
      addressLine1: "Plot 88, SG Highway, Prahlad Nagar",
      city: "Ahmedabad",
      state: "Gujarat",
      postalCode: "380015",
      country: "India",
    },
    city: "Ahmedabad",
    state: "Gujarat",
    postalCode: "380015",
    surveyNumber: "Final Plot No. 88",
    registrationNumber: "REG/AMD/2023/6612",
    deedNumber: "DEED/GJ/2023/4102",
    totalArea: 31000,
    area: "31,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 195000000, // ₹19.50 Cr
    score: "₹19.50 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 16,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2022,
    year: 2022,
    createdByEmail: "arvind.kumar@apexdiligence.in",
    description: "AUDA approved commercial plot on Sarkhej-Gandhinagar Highway. Non-agricultural (NA) conversion certificate fully verified.",
    imageUrl: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1008,
    id: "PR-1008",
    numericId: 1008,
    propertyName: "Vizag IT SEZ Hill No. 3",
    title: "Vizag IT SEZ Hill No. 3",
    ownerName: "Srinivas Raju",
    owner: "Srinivas Raju",
    address: {
      addressLine1: "Plot 12, Rushikonda IT Layout",
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      postalCode: "530045",
      country: "India",
    },
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    postalCode: "530045",
    surveyNumber: "Sy. No. 144/P",
    registrationNumber: "REG/VZG/2023/1109",
    deedNumber: "DEED/AP/2023/7712",
    totalArea: 25000,
    area: "25,000 sq ft",
    landType: "Industrial",
    type: "Industrial",
    marketValue: 98000000, // ₹9.80 Cr
    score: "₹9.80 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 20,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2021,
    year: 2021,
    createdByEmail: "srinivas.raju@apexdiligence.in",
    description: "APIIC SEZ industrial land allotment in Rushikonda with coastal zone CRZ clearances verified by APPCB.",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1009,
    id: "PR-1009",
    numericId: 1009,
    propertyName: "DLF Cyber City Block C",
    title: "DLF Cyber City Block C",
    ownerName: "Sanjay Malhotra",
    owner: "Sanjay Malhotra",
    address: {
      addressLine1: "Phase III, DLF Cyber City",
      city: "Delhi",
      state: "Delhi",
      postalCode: "110037",
      country: "India",
    },
    city: "Delhi",
    state: "Delhi",
    postalCode: "110037",
    surveyNumber: "Khasra No. 891/2",
    registrationNumber: "REG/DL/2024/9912",
    deedNumber: "DEED/DL/2024/1042",
    totalArea: 52000,
    area: "52,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 390000000, // ₹39.00 Cr
    score: "₹39.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 15,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2022,
    year: 2022,
    createdByEmail: "sanjay.malhotra@apexdiligence.in",
    description: "DDA certified commercial office hub with metro connectivity and 100% municipal tax audit clearance.",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1010,
    id: "PR-1010",
    numericId: 1010,
    propertyName: "Kochi SmartCity Tech Zone",
    title: "Kochi SmartCity Tech Zone",
    ownerName: "Radhika Menon",
    owner: "Radhika Menon",
    address: {
      addressLine1: "Kakkanad SmartCity Campus",
      city: "Kochi",
      state: "Kerala",
      postalCode: "682030",
      country: "India",
    },
    city: "Kochi",
    state: "Kerala",
    postalCode: "682030",
    surveyNumber: "Re-Sy. No. 412/4",
    registrationNumber: "REG/KOC/2023/4521",
    deedNumber: "DEED/KL/2023/9011",
    totalArea: 30000,
    area: "30,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 125000000, // ₹12.50 Cr
    score: "₹12.50 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 24,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2020,
    year: 2020,
    createdByEmail: "radhika.menon@apexdiligence.in",
    description: "IT Park land in SmartCity Kakkanad. Kerala State Pollution Control Board clearance verified with clear land title.",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1011,
    id: "PR-1011",
    numericId: 1011,
    propertyName: "Coimbatore Tidel Enclave",
    title: "Coimbatore Tidel Enclave",
    ownerName: "Priya Sundaram",
    owner: "Priya Sundaram",
    address: {
      addressLine1: "Civil Aerodrome Road, Peelamedu",
      city: "Coimbatore",
      state: "Tamil Nadu",
      postalCode: "641014",
      country: "India",
    },
    city: "Coimbatore",
    state: "Tamil Nadu",
    postalCode: "641014",
    surveyNumber: "SF No. 320/1",
    registrationNumber: "REG/CBE/2024/2211",
    deedNumber: "DEED/TN/2024/8812",
    totalArea: 19500,
    area: "19,500 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 86000000, // ₹8.60 Cr
    score: "₹8.60 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 21,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2021,
    year: 2021,
    createdByEmail: "priya.sundaram@apexdiligence.in",
    description: "LPA approved commercial IT land near Tidel Park Coimbatore with clean title & zero encumbrance history.",
    imageUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1012,
    id: "PR-1012",
    numericId: 1012,
    propertyName: "Koramangala Office Tower",
    title: "Koramangala Office Tower",
    ownerName: "Rohan Kulkarni",
    owner: "Rohan Kulkarni",
    address: {
      addressLine1: "100 Feet Road, 4th Block, Koramangala",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560034",
      country: "India",
    },
    city: "Bengaluru",
    state: "Karnataka",
    postalCode: "560034",
    surveyNumber: "Sy. No. 12/4",
    registrationNumber: "REG/BLR/2023/5012",
    deedNumber: "DEED/KA/2023/7711",
    totalArea: 16000,
    area: "16,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 210000000, // ₹21.00 Cr
    score: "₹21.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 19,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2019,
    year: 2019,
    createdByEmail: "rohan.kulkarni@apexdiligence.in",
    description: "Prime Koramangala 100ft road commercial property with complete BBMP Katha extraction and NOCs.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1013,
    id: "PR-1013",
    numericId: 1013,
    propertyName: "Banjara Hills Commercial Plot",
    title: "Banjara Hills Commercial Plot",
    ownerName: "Meera Nambiar",
    owner: "Meera Nambiar",
    address: {
      addressLine1: "Road No. 12, Banjara Hills",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500034",
      country: "India",
    },
    city: "Hyderabad",
    state: "Telangana",
    postalCode: "500034",
    surveyNumber: "Sy. No. 89/1",
    registrationNumber: "REG/HYD/2024/1190",
    deedNumber: "DEED/TS/2024/6612",
    totalArea: 14500,
    area: "14,500 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 225000000, // ₹22.50 Cr
    score: "₹22.50 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 17,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2020,
    year: 2020,
    createdByEmail: "meera.nambiar@apexdiligence.in",
    description: "High-value commercial land parcel in Banjara Hills Road No. 12 with approved HMDA zoning master plan.",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1014,
    id: "PR-1014",
    numericId: 1014,
    propertyName: "Kalyani Nagar Executive Suites",
    title: "Kalyani Nagar Executive Suites",
    ownerName: "Deepak Joshi",
    owner: "Deepak Joshi",
    address: {
      addressLine1: "Plot 42, East Avenue, Kalyani Nagar",
      city: "Pune",
      state: "Maharashtra",
      postalCode: "411006",
      country: "India",
    },
    city: "Pune",
    state: "Maharashtra",
    postalCode: "411006",
    surveyNumber: "CTS No. 182",
    registrationNumber: "REG/PUN/2023/8890",
    deedNumber: "DEED/MH/2023/5012",
    totalArea: 17500,
    area: "17,500 sq ft",
    landType: "Residential",
    type: "Residential",
    marketValue: 154000000, // ₹15.40 Cr
    score: "₹15.40 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 16,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2021,
    year: 2021,
    createdByEmail: "deepak.joshi@apexdiligence.in",
    description: "PMC verified luxury residential land in Kalyani Nagar with nil litigation certificate from Pune District Court.",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
  },
  {
    propertyId: 1015,
    id: "PR-1015",
    numericId: 1015,
    propertyName: "Worli Sea Face Commercial Parcel",
    title: "Worli Sea Face Commercial Parcel",
    ownerName: "Sunita Agarwal",
    owner: "Sunita Agarwal",
    address: {
      addressLine1: "Plot 99, Dr. E. Moses Road, Worli",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400018",
      country: "India",
    },
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400018",
    surveyNumber: "CTS No. 702/A",
    registrationNumber: "REG/MAH/2024/1102",
    deedNumber: "DEED/MH/2024/9912",
    totalArea: 29000,
    area: "29,000 sq ft",
    landType: "Commercial",
    type: "Commercial",
    marketValue: 520000000, // ₹52.00 Cr
    score: "₹52.00 Cr",
    status: "Verified Clear Title",
    variant: "success",
    riskScore: 11,
    riskLevel: "Low Risk",
    riskStatus: "LOW",
    builtYear: 2023,
    year: 2023,
    createdByEmail: "sunita.agarwal@apexdiligence.in",
    description: "Ultra-prime Worli sea-facing land parcel with full MCGB building permission and Coastal Regulation Zone clearance.",
    imageUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    image: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
  },
];

// Generate 20 additional properties to reach 35+ properties
const additionalCities = [
  { city: "Hyderabad", state: "Telangana", code: "HYD" },
  { city: "Bengaluru", state: "Karnataka", code: "BLR" },
  { city: "Chennai", state: "Tamil Nadu", code: "CHE" },
  { city: "Mumbai", state: "Maharashtra", code: "MAH" },
  { city: "Pune", state: "Maharashtra", code: "PUN" },
  { city: "Delhi", state: "Delhi", code: "DL" },
  { city: "Ahmedabad", state: "Gujarat", code: "AMD" },
  { city: "Visakhapatnam", state: "Andhra Pradesh", code: "VZG" },
  { city: "Coimbatore", state: "Tamil Nadu", code: "CBE" },
  { city: "Kochi", state: "Kerala", code: "KOC" },
];

const indianNames = [
  "Ramesh Kumar", "Venkatesh Iyer", "Suresh Patel", "Ananya Rao", "Vikramaditya Reddy",
  "Aditi Deshmukh", "Kavitha Nair", "Arvind Kumar", "Srinivas Raju", "Radhika Menon",
  "Rohan Kulkarni", "Meera Nambiar", "Deepak Joshi", "Sanjay Malhotra", "Sunita Agarwal",
  "Priya Sundaram", "Rajesh Sharma", "Nikhil Verma", "Pooja Hegde", "Tarun Kapoor",
];

const propertyTypes = ["Commercial", "Residential", "Industrial", "Mixed-Use"];

const sampleRealEstateImages = [
  "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
];

for (let i = 16; i <= 35; i++) {
  const c = additionalCities[(i - 16) % additionalCities.length];
  const owner = indianNames[(i - 16) % indianNames.length];
  const type = propertyTypes[i % propertyTypes.length];
  const sqft = 10000 + (i * 1250);
  const val = (50 + i * 8.5) * 1000000;
  const risk = (i % 7 === 0) ? 72 : (i % 4 === 0) ? 44 : 15 + (i % 15);
  const status = risk > 70 ? "Tax Audit Pending" : risk > 35 ? "Minor Variance Pending" : "Verified Clear Title";
  const variant = risk > 70 ? "danger" : risk > 35 ? "warning" : "success";
  const imageToUse = sampleRealEstateImages[i % sampleRealEstateImages.length];

  INDIAN_PROPERTIES.push({
    propertyId: 1000 + i,
    id: `PR-${1000 + i}`,
    numericId: 1000 + i,
    propertyName: `${c.city} Prime Sector ${i - 15} Parcel`,
    title: `${c.city} Prime Sector ${i - 15} Parcel`,
    ownerName: owner,
    owner: owner,
    address: {
      addressLine1: `Plot ${i * 4}, Sy. No. ${100 + i}/A, Main Tech Avenue`,
      city: c.city,
      state: c.state,
      postalCode: `${500000 + i * 111}`,
      country: "India",
    },
    city: c.city,
    state: c.state,
    postalCode: `${500000 + i * 111}`,
    surveyNumber: `Sy. No. ${100 + i}/A`,
    registrationNumber: `REG/${c.code}/2024/${4000 + i}`,
    deedNumber: `DEED/${c.code}/2024/${8000 + i}`,
    totalArea: sqft,
    area: `${sqft.toLocaleString()} sq ft`,
    landType: type,
    type: type,
    marketValue: val,
    score: `₹${(val / 10000000).toFixed(2)} Cr`,
    status: status,
    variant: variant,
    riskScore: risk,
    riskLevel: risk > 70 ? "High Risk" : risk > 35 ? "Moderate Risk" : "Low Risk",
    riskStatus: risk > 70 ? "HIGH" : risk > 35 ? "MEDIUM" : "LOW",
    builtYear: 2018 + (i % 6),
    year: 2018 + (i % 6),
    createdByEmail: `${owner.toLowerCase().replace(" ", ".")}@apexdiligence.in`,
    description: `Verified enterprise property parcel located in ${c.city}, ${c.state}. Clear title search, municipal zoning compliant, and encumbrance verified.`,
    imageUrl: imageToUse,
    image: imageToUse,
  });
}

// Ownership Chain of Title Records Generator
export const getMockOwnershipRecords = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);
  const currentProp = INDIAN_PROPERTIES.find((p) => p.numericId === numericId) || INDIAN_PROPERTIES[0];

  return [
    {
      ownerName: currentProp.ownerName,
      registrationNumber: currentProp.registrationNumber,
      deedNumber: currentProp.deedNumber,
      startDate: "2023-04-12",
      endDate: "Present",
      ownershipType: "Outright Sale Deed",
      isCurrentOwner: true,
      status: "Verified Active Deed",
      encumbranceStatus: "Nil Encumbrance",
      subRegistrarOffice: `${currentProp.city} Central Sub-Registrar`,
    },
    {
      ownerName: "Venkatesh Iyer",
      registrationNumber: `REG/${currentProp.city.slice(0, 3).toUpperCase()}/2018/4410`,
      deedNumber: "DEED/TS/2018/1209",
      startDate: "2018-09-20",
      endDate: "2023-04-11",
      ownershipType: "Partition Deed",
      isCurrentOwner: false,
      status: "Transferred",
      encumbranceStatus: "Discharged",
      subRegistrarOffice: `${currentProp.city} Central Sub-Registrar`,
    },
    {
      ownerName: "Srinivas Raju & Sons",
      registrationNumber: `REG/${currentProp.city.slice(0, 3).toUpperCase()}/2010/8812`,
      deedNumber: "DEED/TS/2010/3341",
      startDate: "2010-01-15",
      endDate: "2018-09-19",
      ownershipType: "Ancestral Inheritance",
      isCurrentOwner: false,
      status: "Historical",
      encumbranceStatus: "Cleared",
      subRegistrarOffice: `${currentProp.city} District Registry`,
    },
  ];
};

// Municipal Tax Audit History Generator
export const getMockTaxRecords = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);

  return [
    { assessmentYear: "2024-2025", taxAmount: 145000, taxStatus: "Paid", paymentDate: "2024-05-10", receiptNumber: `TX-${numericId}-2024-9912` },
    { assessmentYear: "2023-2024", taxAmount: 138000, taxStatus: "Paid", paymentDate: "2023-05-14", receiptNumber: `TX-${numericId}-2023-8811` },
    { assessmentYear: "2022-2023", taxAmount: 130000, taxStatus: "Paid", paymentDate: "2022-04-28", receiptNumber: `TX-${numericId}-2022-7741` },
    { assessmentYear: "2021-2022", taxAmount: 125000, taxStatus: "Paid", paymentDate: "2021-05-02", receiptNumber: `TX-${numericId}-2021-6602` },
    { assessmentYear: "2020-2021", taxAmount: 118000, taxStatus: "Paid", paymentDate: "2020-04-19", receiptNumber: `TX-${numericId}-2020-5510` },
  ];
};

// Building Permit Records Generator
export const getMockPermitRecords = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);

  return [
    { permitId: 4410, permitNumber: `MNC-BP-${numericId}-2023`, permitType: "Commercial High-Rise Construction", permitStatus: "Approved & Active", issueDate: "2023-01-15", expiryDate: "2028-01-14", issuingAuthority: "Municipal Planning Board" },
    { permitId: 4411, permitNumber: `MNC-OC-${numericId}-2023`, permitType: "Occupancy Certificate (OC)", permitStatus: "Certified Verified", issueDate: "2023-08-20", expiryDate: "Permanent", issuingAuthority: "Department of Building Inspection" },
    { permitId: 4412, permitNumber: `MNC-FIRE-${numericId}-2022`, permitType: "Fire Safety NOC Clearance", permitStatus: "Active", issueDate: "2022-11-10", expiryDate: "2027-11-09", issuingAuthority: "State Disaster Management Force" },
  ];
};

// Environmental Hazards Audit Generator
export const getMockEnvironmentalRecords = (propertyId = "1001") => {
  return [
    {
      clearanceStatus: "Approved Phase I SPCB Environmental Clearance",
      environmentalRisks: "Zero Soil Contamination Detected. Heavy Metal Residue Index: 0.00 ppm.",
      pollutionInfo: "Groundwater Quality Index: 98/100 (Safe). Air Quality AQI: 42 (Good). Ambient Noise Level: 45 dB.",
      hazardClassification: "Category Green (Clean Industrial / Commercial)",
      auditDate: "2024-02-18",
    },
    {
      clearanceStatus: "State Pollution Control Board NOC",
      environmentalRisks: "No hazardous chemical waste dumping reported within 2.5 km radius.",
      pollutionInfo: "Effluent Treatment Plant (ETP) connection certified compliant.",
      hazardClassification: "Low Hazard Index",
      auditDate: "2023-06-12",
    },
  ];
};

// Flood Plain & Elevation Survey Generator
export const getMockFloodZoneRecords = (propertyId = "1001") => {
  return {
    floodRisk: "Low Risk",
    floodZone: "Zone X (Unshaded - Above 100-Yr Flood Plain)",
    insuranceRequired: false,
    lastUpdated: "2024-01-10",
    elevationFeet: 485,
    drainageCapacity: "Grade A Municipal Stormwater Network",
  };
};

// Municipal Zoning Information Generator
export const getMockZoningRecords = (propertyId = "1001") => {
  return {
    zoningCode: "C-3 Commercial Business District",
    zoningClassification: "Commercial High-Density",
    maxFar: 3.50,
    currentFar: 2.85,
    maxBuildingHeight: "60 Meters",
    setbackRequirements: "Front: 6m, Rear: 4m, Sides: 3m",
    parkingNorms: "1 ECS per 50 sq. m. built-up area",
  };
};

// Vector Risk Assessment Generator
export const getMockRiskAssessment = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);
  const currentProp = INDIAN_PROPERTIES.find((p) => p.numericId === numericId) || INDIAN_PROPERTIES[0];

  return {
    propertyId: `PR-${currentProp.numericId}`,
    propertyName: currentProp.propertyName,
    address: `${currentProp.address.addressLine1}, ${currentProp.city}, ${currentProp.state}`,
    overallScore: 100 - currentProp.riskScore,
    riskLevel: currentProp.riskLevel,
    recommendation: currentProp.riskScore > 60 ? "FLAGGED FOR SPECIAL REVIEW" : "APPROVED FOR ACQUISITION",
    verdictDescription: `Land title search and sub-registrar verification completed for ${currentProp.propertyName}. Title clear of encumbrances and litigation.`,
    categories: [
      { id: "legal", title: "Legal & Litigation Risk", score: 95, status: "Low Risk", variant: "success", details: "Court search clear." },
      { id: "ownership", title: "Ownership & Encumbrance", score: 92, status: "Low Risk", variant: "success", details: "Deed verified." },
      { id: "tax", title: "Municipal Property Tax", score: 96, status: "Low Risk", variant: "success", details: "Tax receipts clear." },
      { id: "flood", title: "Flood & Elevation Risk", score: 88, status: "Low Risk", variant: "success", details: "Flood map safe." },
      { id: "environmental", title: "Environmental Hazards", score: 90, status: "Low Risk", variant: "success", details: "Pollution NOC clear." },
      { id: "zoning", title: "Zoning & Permit Compliance", score: 85, status: "Low Risk", variant: "success", details: "Zoning FAR verified." },
    ],
  };
};

// Comparable Market Properties Generator
export const getMockComparableProperties = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);
  const currentProp = INDIAN_PROPERTIES.find((p) => p.numericId === numericId) || INDIAN_PROPERTIES[0];

  return INDIAN_PROPERTIES.filter((p) => p.city === currentProp.city && p.numericId !== currentProp.numericId).slice(0, 6);
};

// Generated Due Diligence Audit Reports Archive
export const getMockDueDiligenceReports = () => {
  return [
    {
      id: "RPT-2024-1001",
      name: "Comprehensive Diligence Audit - Gachibowli Tech Park Phase 2",
      propertyName: "Gachibowli Tech Park Phase 2",
      city: "Hyderabad",
      date: "2024-06-15",
      status: "Completed",
      variant: "success",
      score: 86,
    },
    {
      id: "RPT-2024-1002",
      name: "Title & Tax Verification - Jubilee Hills Luxury Enclave",
      propertyName: "Jubilee Hills Luxury Enclave",
      city: "Hyderabad",
      date: "2024-06-12",
      status: "Completed",
      variant: "success",
      score: 82,
    },
    {
      id: "RPT-2024-1003",
      name: "Environmental & Risk Audit - Whitefield ORR Tech Hub",
      propertyName: "Whitefield Outer Ring Road Tech Hub",
      city: "Bengaluru",
      date: "2024-06-08",
      status: "Completed",
      variant: "success",
      score: 78,
    },
    {
      id: "RPT-2024-1004",
      name: "Commercial Land Audit - Bandra Kurla Complex Tower",
      propertyName: "Bandra Kurla Complex Corporate Tower",
      city: "Mumbai",
      date: "2024-05-28",
      status: "Completed",
      variant: "success",
      score: 88,
    },
    {
      id: "RPT-2024-1005",
      name: "Zoning & Far Compliance Audit - OMR IT Corridor",
      propertyName: "OMR IT Corridor Parcel A",
      city: "Chennai",
      date: "2024-05-14",
      status: "Completed",
      variant: "success",
      score: 72,
    },
  ];
};

// System Notifications & Real-Time Alerts
export const getMockNotifications = () => {
  return [
    { id: 1, title: "Title Deed Verification Completed", message: "Sub-Registrar clearance certificate generated for PR-1001.", timestamp: "10 mins ago", type: "success", read: false },
    { id: 2, title: "Municipal Tax Assessment Verified", message: "Tax receipts paid up to assessment year 2024-2025.", timestamp: "1 hour ago", type: "info", read: false },
    { id: 3, title: "Environmental Clearance Confirmed", message: "State Pollution Control Board approved Phase I audit.", timestamp: "3 hours ago", type: "success", read: true },
    { id: 4, title: "New High-Value Property Added", message: "BKC Corporate Tower parcel added to active watch list.", timestamp: "Yesterday", type: "info", read: true },
    { id: 5, title: "Zoning Variance Audit Complete", message: "FAR permissions confirmed for Whitefield Tech Hub.", timestamp: "2 days ago", type: "success", read: true },
  ];
};

// Audit Logs & Activity Event Feeds
export const getMockAuditLogs = () => {
  return [
    { id: "LOG-9901", user: "Rajesh Sharma", action: "Executed Title Deed Verification", module: "Sub-Registrar Registry", timestamp: "Today, 10:45 AM", ip: "192.168.1.104", status: "SUCCESS" },
    { id: "LOG-9902", user: "Ananya Rao", action: "Exported Due Diligence PDF Dossier", module: "Report Engine", timestamp: "Today, 09:30 AM", ip: "192.168.1.108", status: "SUCCESS" },
    { id: "LOG-9903", user: "Venkatesh Iyer", action: "Queried Municipal Tax Receipts", module: "Tax Assessment", timestamp: "Yesterday, 04:15 PM", ip: "192.168.1.112", status: "SUCCESS" },
    { id: "LOG-9904", user: "Suresh Patel", action: "Ran Environmental Hazard Assessment", module: "SPCB Audit Engine", timestamp: "Yesterday, 02:20 PM", ip: "192.168.1.115", status: "SUCCESS" },
    { id: "LOG-9905", user: "Aditi Deshmukh", action: "Updated Property Watch List", module: "Portfolio Manager", timestamp: "2 days ago", ip: "192.168.1.120", status: "SUCCESS" },
  ];
};

// Executive Dashboard & Telemetry KPI Statistics
export const getMockDashboardStats = () => {
  return {
    totalProperties: 1482,
    completedReports: 1240,
    pendingReports: 182,
    highRiskProperties: 24,
    mediumRiskProperties: 118,
    lowRiskProperties: 1340,
    recentSearchesCount: 384,
    savedPropertiesCount: 28,
    activeAuditsCount: 14,
    riskDistribution: [
      { name: "Low Risk", value: 1340, percentage: "90%" },
      { name: "Medium Risk", value: 118, percentage: "8%" },
      { name: "High Risk", value: 24, percentage: "2%" },
    ],
    propertyTypesDistribution: [
      { name: "Commercial", value: 666 },
      { name: "Residential", value: 518 },
      { name: "Industrial", value: 178 },
      { name: "Mixed-Use", value: 120 },
    ],
    monthlyReportTrends: [
      { month: "Jan", reports: 85, verified: 80 },
      { month: "Feb", reports: 92, verified: 88 },
      { month: "Mar", reports: 110, verified: 104 },
      { month: "Apr", reports: 125, verified: 118 },
      { month: "May", reports: 140, verified: 132 },
      { month: "Jun", reports: 165, verified: 158 },
    ],
  };
};

// Master Indian Utility Infrastructure Records Generator
export const getMockUtilityRecords = (propertyId = "1001") => {
  const numericId = parseInt(propertyId.toString().replace(/\D/g, "") || "1001", 10);
  return [
    { serviceType: "Electricity Grid Connection", provider: "State Electricity Distribution Corp (TSSPDCL / BESCOM / MSEDCL)", connectionStatus: "Connected & Active", meterNumber: `MTR-ELE-${numericId}-9981`, loadCapacity: "500 KVA High Tension", statusVariant: "success" },
    { serviceType: "Municipal Water Supply", provider: "Metro Water Supply & Sewerage Board", connectionStatus: "Connected & Active", meterNumber: `MTR-WTR-${numericId}-4412`, loadCapacity: "100,000 Litres/Day", statusVariant: "success" },
    { serviceType: "Sewage & Effluent System", provider: "Municipal Corporation Sewerage Division", connectionStatus: "Connected & Certified", meterNumber: `SEW-${numericId}-1102`, loadCapacity: "Grade A Underground Network", statusVariant: "success" },
    { serviceType: "High-Speed Fiber Broadband", provider: "Airtel / Jio Enterprise Fiber Network", connectionStatus: "Active Dual-Path Fiber", meterNumber: `FBR-${numericId}-8810`, loadCapacity: "10 Gbps Redundant Line", statusVariant: "success" },
  ];
};

// Master Indian User Profile
export const getMockUserProfile = () => {
  return {
    name: "Rajesh Sharma",
    email: "rajesh.sharma@apexdiligence.in",
    role: "Senior Diligence Architect & Legal Lead",
    organization: "Apex Due Diligence Advisors India Pvt. Ltd.",
    phone: "+91 98490 12345",
    address: "Plot 45, Sy. No. 112/A, Financial District, Nanakramguda",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    department: "Land Records & Legal Compliance",
    completedReportsCount: 142,
    savedPropertiesCount: 28,
    totalSearchesCount: 1240,
    riskAssessmentsCount: 980,
  };
};
