spring.application.name=real-estate-due-diligence-agent

spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
